#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma once

#include <xtd/xtd>

namespace cron_gui::properties {
  /// @brief A strongly typed settings class, for storing user and system settings
  /// @details This class was auto-generated by CMake script. To add or remove a member, edit your CMakeList.txt or properties/settings.cmake file then rerun cmake tools.
  /// @remarks See <a href=https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.core/settings>Settings</a> for more informations.
  class settings : public xtd::forms::component {
  public:
    /// @brief Initializes a new instance of the cron_gui::properties::settings class.
    settings() : ::cron_gui::properties::settings(true) {}

    /// @brief Gets the default instance of settings.
    /// @return The default instance.
    static ::cron_gui::properties::settings& default_settings() {
      static ::cron_gui::properties::settings default_settings;
      return default_settings;
    }

    /// @brief Gets the location user setting property.
    /// @return A xtd::drawing::point value.
    xtd::drawing::point location() const {return location_;}
    /// @brief Sets the location user setting property.
    /// @param value A xtd::drawing::point value.
    void location(xtd::drawing::point value) {location_ = value;}

    /// @brief Gets the client_size user setting property.
    /// @return A xtd::drawing::size value.
    xtd::drawing::size client_size() const {return client_size_;}
    /// @brief Sets the client_size user setting property.
    /// @param value A xtd::drawing::size value.
    void client_size(xtd::drawing::size value) {client_size_ = value;}

    /// @brief Reload all properties with the last saved values.
    /// @remarks See <a href=https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.core/settings>Settings</a> for more informations.
    void reload() {
      location_ = settings_.read("location", location_);
      client_size_ = settings_.read("client_size", client_size_);
    }

    /// @brief Reset all properties to their default values.
    /// @remarks See <a href=https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.core/settings>Settings</a> for more informations.
    void reset() {
      settings_.reset();
      *this = settings(false);
      reload();
    }

    /// @brief Save all properties.
    /// @remarks See <a href=https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.core/settings>Settings</a> for more informations.
    void save() {
      settings_.write("location", location_);
      settings_.write("client_size", client_size_);
      settings_.save();
    }

  private:
    explicit settings(bool load) {if (load) reload();}
    xtd::forms::settings settings_;
    xtd::drawing::point location_ {{100, 50}};
    xtd::drawing::size client_size_ {{800, 450}};
  };
}

#pragma endregion
