#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma once

#include <xtd/xtd>

namespace cron_gui::properties {
  class settings : public xtd::forms::component {
  public:
    settings() : ::cron_gui::properties::settings(true) {}

    static ::cron_gui::properties::settings& default_settings() {
      static ::cron_gui::properties::settings default_settings;
      return default_settings;
    }

    xtd::drawing::point location() const {return location_;}
    void location(xtd::drawing::point value) {location_ = value;}

    xtd::drawing::size client_size() const {return client_size_;}
    void client_size(xtd::drawing::size value) {client_size_ = value;}

    void reload() {
      location_ = settings_.read("location", location_);
      client_size_ = settings_.read("client_size", client_size_);
    }

    void reset() {
      settings_.reset();
      *this = settings(false);
      reload();
    }

    void save() {
      settings_.write("location", location_);
      settings_.write("client_size", client_size_);
      settings_.save();
    }

  private:
    explicit settings(bool load) {if (load) reload();}
    xtd::forms::settings settings_;
    xtd::drawing::point location_ {{100, 50}};
    xtd::drawing::size client_size_ {{800, 450}};
  };
}

#pragma endregion
